### ISSUE TITLE
Problem raising while testing the model

### ISSUE THREAD

**Issue by tinkubhanu216** [spthermo/generative-image-inpainting#1]
The model was saved in the format of tar(netG_e1.pth.tar).  Error raising while running inpainting.py with argument of netG_e1.pth.tar

**Comment by spthermo** [comment]
Can you share the error? In general if you cannot load the model as is, try something like:
`checkpoint = torch.load(opt.netG)`
`netG.load_state_dict(checkpoint['state_dict'])`

**Comment by vlzzhou** [comment]
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "main.0.weight", "main.0.bias", "main.1.weight", "main.1.bias", "main.1.running_mean", "main.1.running_var", "main.3.weight", "main.3.bias", "main.4.weight", "main.4.bias", "main.4.running_mean", "main.4.running_var", "main.6.weight", "main.6.bias", "main.7.weight", "main.7.bias", "main.7.running_mean", "main.7.running_var", "main.9.weight", "main.9.bias", "main.10.weight", "main.10.bias", "main.10.running_mean", "main.10.running_var", "main.12.weight", "main.12.bias", "main.13.weight", "main.13.bias", "main.13.running_mean", "main.13.running_var", "main.15.weight", "main.15.bias", "main.16.weight", "main.16.bias", "main.16.running_mean", "main.16.running_var", "main.18.weight", "main.18.bias", "main.19.weight", "main.19.bias", "main.19.running_mean", "main.19.running_var", "main.21.weight", "main.21.bias", "main.22.weight", "main.22.bias", "main.22.running_mean", "main.22.running_var", "main.24.weight", "main.24.bias", "main.25.weight", "main.25.bias", "main.25.running_mean", "main.25.running_var", "main.27.weight", "main.27.bias", "main.28.weight", "main.28.bias", "main.28.running_mean", "main.28.running_var", "main.30.weight", "main.30.bias", "main.31.weight", "main.31.bias", "main.31.running_mean", "main.31.running_var", "main.33.weight", "main.33.bias", "main.34.weight", "main.34.bias", "main.34.running_mean", "main.34.running_var", "main.36.weight", "main.36.bias", "main.37.weight", "main.37.bias", "main.37.running_mean", "main.37.running_var", "main.39.weight", "main.39.bias", "main.40.weight", "main.40.bias", "main.40.running_mean", "main.40.running_var", "main.42.weight", "main.42.bias", "main.43.weight", "main.43.bias", "main.43.running_mean", "main.43.running_var", "main.45.weight", "main.45.bias", "main.46.weight", "main.46.bias", "main.46.running_mean", "main.46.running_var", "main.48.weight", "main.48.bias". 
	Unexpected key(s) in state_dict: "epoch", "state_dict", "optimizer". 
Maybe he was talking about this problem
